version: "3"
services:
  zk:
    image: wurstmeister/zookeeper
    hostname: zk
    ports:
      - "2181:2181"
    container_name: zkd

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    hostname: kafka
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_LISTENERS: INSIDE://kafka:19092,CLIENT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:19092,CLIENT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: test:1:1,pizza_logger:1:1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_BROKER_ID: 999
    container_name: kafka

networks:
   default:
      external:
        name: net
